class CreateUsers < ActiveRecord::Migration
  # The following was automatically generated by rails when generating model
  # Note this result differs from what was generatesd in the railstutorial
  
  # def change
  #  create_table :users do |t|
  #   t.string :name
  #    t.string :email

  #    t.timestamps
  #  end
  # end
  
  # The following is is what is generate in the railstutorial
  
  # class CreateUsers < ActiveRecord::Migration
  def self.up
    create_table :users do |t|
      t.string :name
      t.string :email

      t.timestamps
    end
  end

  def self.down
    drop_table :users
  end
end
